### ISSUE TITLE
timing information

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#11]
analyse timing information

**Comment by euhruska** [comment]
it looks like we need to name the tasks to distinguish the timing of MD simulations, lsdmap, and other tasks

**Comment by vivek-bala** [comment]
Unfortunately, the name of the task doesn't appear in the profiles. You would require  a mapping between the task uids and the task names. You can get the unit ids from the task ids if required.

**Comment by euhruska** [comment]
would adding post_ana_task._name      = 'post_ana_task'  work?

**Comment by vivek-bala** [comment]
That post_ana_task object would get the name. But the profiler does not pick the name of the object so you don't see it in the profiles.

**Comment by euhruska** [comment]
hmm, it looks like a workaround works:
```
if 'lsdmap' in str(unit[i].description):
```
Is there a way to get the iteration of a unit from the profiler?

**Comment by euhruska** [comment]
solved with commit https://github.com/radical-collaboration/extasy-grlsd/commit/0be31645aca2a09123510d76801c2f558ccfc8df

**Comment by euhruska** [comment]
the timing information is currently extracted with analytics_timing.py and saved at timing_output.txt
