### ISSUE TITLE
old issue

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#12]
similar issue to https://bitbucket.org/extasy-project/extasy-workflows/issues/18/gmxcoco-workflow-failing-on-blue-waters, how did we solve it?
```
Sat Jan  6 09:13:25 2018: [unset]:_pmi_alps_sync:alps response not OKAY
Sat Jan  6 09:13:25 2018: [unset]:_pmiu_daemon:_pmi_alps_sync failed
run.sh: line 16: 29512 Aborted                 gmx grompp -f grompp.mdp -c $tmpstartgro -p topol.top -o topol.tpr
Sat Jan  6 09:13:25 2018: [PE_0]:_pmi_daemon_barrier:PE pipe read failed from daemon errno = Success
Sat Jan  6 09:13:25 2018: [PE_0]:_pmi_init:_pmi_daemon_barrier returned -1
```

**Comment by vivek-bala** [comment]
Following the same ticket, it seems like the issue earlier was a conflicting environment setup in the bashrc. Do you have anything in your bashrc that might conflict with the environment required by gromacs?

**Comment by euhruska** [comment]
probably, this issue doesn't happen anymore, so going to close it
