### ISSUE TITLE
high CPU load on local 

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#13]
Even when just waiting for heartbeats the local extasy-grlsd takes almost 100% of the CPU on the local computer. Is there a reason for this?

**Comment by euhruska** [comment]
it seem to not affect the performance

**Comment by vivek-bala** [comment]
This is expected currently. IIRC all but one of the processes (and threads) are continuously checking if any tasks are finished and whether new tasks need to be submitted. I'll open a ticket in EnTK to add any throttling mechanism by sleeping the processes and threads via an environment variable. Thanks!

**Comment by vivek-bala** [comment]
VB/FB to create documentation regarding setup on Jetstream.
