### ISSUE TITLE
assert OMP_NUM_THREADS

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#14]
pyemma does an assertion of omp_get_num_threads()
```
 omp_set_num_threads(n_threads);
 assert(omp_get_num_threads() == n_threads);
```
and this leads to the error 
```
python: pyemma/coordinates/clustering/src/clustering.c:95: c_assign: Assertion `omp_get_num_threads() == n_threads' failed.
```
when setting ```export OMP_NUM_THREADS=1```, then this works
@vivek-bala is there a part of entk which could set this correctly

**Comment by vivek-bala** [comment]
Hey Eugen, correct me if I misunderstood your question: You are asking for a method by which you can add 
```export OMP_NUM_THREADS=1``` before each task executes the pyemma command. Correct?

If so, you can do it by using the ```pre_exec``` property of a Task:
``` task.pre_exec = ['export OMP_NUM_THREADS=1'] ```

Let me know how it goes.

**Comment by andre-merzky** [comment]
`pre_exec` env settings won't help you with ORTE.  Env settings should go into the CU `environment` dict anyway.  Does the EnTK task expose that?

**Comment by euhruska** [comment]
fixed with https://github.com/markovmodel/PyEMMA/issues/1346#issuecomment-411321664
