### ISSUE TITLE
python path

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#18]
To fix in branch 'no_fail' the below issues I have tried setting the Path in pre_exec, but still post_analyze.py didn't use my python but used the default python. Only I set the full correct python path for post_analyze.py then it worked. @vivek-bala how do I set the python paths correctly?
https://github.com/radical-collaboration/extasy-grlsd/issues/7
https://github.com/radical-collaboration/extasy-grlsd/issues/10

**Comment by vivek-bala** [comment]
I commented #7. Please see.

Line [200](https://github.com/radical-collaboration/extasy-grlsd/blob/no_fail/extasy_grlsd.py#L200) and [203](https://github.com/radical-collaboration/extasy-grlsd/blob/no_fail/extasy_grlsd.py#L203) seem to be conflicting. Currently, the python you are pointing in line 203 is what is going to be picked up. Is that intended?
