### ISSUE TITLE
MD task works but reports failed state

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#2]
the MD task works as intended, but reports a FAILED state 

```
2017-12-20 12:51:28,929: radical.entk.appmanager: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.task.0028 with state FAILED
Syncing task radical.entk.task.0028 with state FAILED
Synced task radical.entk.task.0028 with state FAILED
```
Possibly a mismatch of number of lines, see:
https://github.com/radical-collaboration/extasy-grlsd/blob/master/helper_scripts/run.py#L93-L94

**Comment by vivek-bala** [comment]
Yes, I am not sure why the number of lines are not different. I leave it to you either remove the assert statement and check why the number of lines are different.

**Comment by euhruska** [comment]
Didn't work, not sure why

**Comment by vivek-bala** [comment]
Hey Eugen, as I mentioned the error is coming from the assertion in line https://github.com/radical-collaboration/extasy-grlsd/blob/master/helper_scripts/run.py#L93-L94.

I am not sure why the number of lines in the new file is different from the input file. But if you think it is expected/correct, please remove the above assertion in line 93-94 and you shouldn't see FAILED tasks. Let me know how it goes.

**Comment by euhruska** [comment]
removing that assertion work, but it means losing about 10% of all structures, which is not acceptable.
run.sh works perfectly when I run myself ```sh run.sh```, but the same script and inputs fail about 10% time when run by extasy-grlsd. Do you know why there is this difference in behavior?
I'm not sure what's going on, but it looks like the grompp or mdrun commands fail with a small probability and never produce the output structures.
I tried adding sleep and wait commands, but it still it fails.

**Comment by euhruska** [comment]
With sleep for 2 sec run.sh works but with sleep 0.1 sec it fails. That's a temporary solution.

**Comment by vivek-bala** [comment]
The error is coming from the gromacs layer. Do you think there might be something wrong with gromacs installation on BW? If you have a specific version in mind, we should install that and test using that. I am not exactly sure why the error comes up either, I can confirm running the run.sh manually works for me as well.

**Comment by euhruska** [comment]
The gromacs logs look OK,  except some which are cut off. That a longer sleep command helps means that gromacs would properly  finish it's task,  but something cuts gromacs off. I haven't heard of that kind of installation error with gromacs

**Comment by euhruska** [comment]
If you think it makes sense,  could try openmm instead gromacs

**Comment by vivek-bala** [comment]
It's your call :) EnTK script should be invariant to it.

**Comment by euhruska** [comment]
the branch "no_fail" implements the sleep, but works only if the sleep is longer than the MD simulation.

**Comment by euhruska** [comment]
Solved in openmm branch, still unclear why this is not an issue with openmm but with gromacs, since the entk script should be invariant to it.
