### ISSUE TITLE
option TICA

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#27]

**Comment by euhruska** [comment]
the TICA and Lsdmap extasy are >50% different, the analysis and post-analysis units are totally different do you think we should have two separate scripts or one with options determining which out of two units will be used?

**Comment by vivek-bala** [comment]
My suggestion would be to have two different scripts. Going forward, it will be harder to keep one script stable, up-to-date and bug-free for both lsdmap and tica.

**Comment by euhruska** [comment]
I can see that keeping them stable would be easier, but just having one script would make easier to compare these two approaches later, as I want to do. What's your opinion?

**Comment by vivek-bala** [comment]
I understand. But based on my experience I will still suggest using two scripts. I remember the time when I tried to support both gmx-lsdmap and gmx-coco using once script. It was not good :)

**Comment by vivek-bala** [comment]
code maintenance > code execution. You can automate the latter.

**Comment by euhruska** [comment]
got it, thanks

Quoting "Vivekanandan (Vivek) Balasubramanian" <notifications@github.com>:
