### ISSUE TITLE
execution stops at unit 18

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#32]
execution until unit 18 (lsdmap), it finishes (shown in 
profiler) and then the next unit is not created at all, only heartbeat for an hour
logs in [rp.session.EugenHruska.local.eh.017550.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1648313/rp.session.EugenHruska.local.eh.017550.0005.zip)

**Comment by euhruska** [comment]
reinstalled on different VM, works

**Comment by vivek-bala** [comment]
Alrighty! We just get our allocation resumed on Jetstream. In case you need Jetstream in the future.

**Comment by euhruska** [comment]
Thanks, it works not so not going to change that
