### ISSUE TITLE
instructions to run on remote VM?

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#33]
Can the instructions how to run on a remote VM be shared?

**Comment by andre-merzky** [comment]
Hi @euhruska - I am not sure I understand the question.  Is this about how RP can use a VM as target for a pilot?  Then sharing is no different from any other machine: you create additional user accounts under which users can submit pilots.  As for resource management: for that you'll either need to set up quota per user, or install a batch system.

I might be totally off with the above - let me know...

**Comment by euhruska** [comment]
No, it's a follow-up to last tuesday. I don't want to run extasy exclusively from my laptop, so we wanted to run the local part of extasy on a VM. The remote part will still be on bluewaters. No changes to quotas or user accounts. Are there previous instructions how to do a setup on a VM (Amazon, jetstream, similar) to run extasy?

**Comment by andre-merzky** [comment]
I can't speak much for extasy itself - but RP should need nothing special other than a functional python stack with all dependencies.  You'll also presumable need gsissh and myproxy installed to get the BW access part configured properly.  The VM really should behave no different than your laptop...

**Comment by euhruska** [comment]
I assumed that much, but is there a VM which is recommended?

**Comment by shantenujha** [comment]
- JetStream.

- In the worst case,  "AWS account with access under the free tier” is an option.

**Comment by euhruska** [comment]
It seems my xsede account doesn't have access to Atmosphere, when login into https://use.jetstream-cloud.org.

**Comment by euhruska** [comment]
The free AWS tier has very low storage, so it's hard to install everything necessary there.
But I have debugged the setup on another machine (leonardo) in our group, and I'm able to launch extasy from there. Solved
