### ISSUE TITLE
unit 0 finished then nothing happens

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#35]
This doesn't happen always, but here the unit 0 is finished (cu_exec_stop) and then instead of starting next unit it just heartbeats. Can you check the logs?
[rp.session.leonardo.rice.edu.eh22.017555.0002.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1662104/rp.session.leonardo.rice.edu.eh22.017555.0002.zip)
[rp.session.leonardo.rice.edu.eh22.017555.0002-remote.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1662112/rp.session.leonardo.rice.edu.eh22.017555.0002-remote.zip)

**Comment by vivek-bala** [comment]
Unit 0 completes successfully but the next task is not even submitted. Do you happen to when you saw this issue, as in: Was the environment the same as the one for the successful runs? Was this run after a failed run by any chance (where you had to Ctrl+c or Ctrl+z)?

And how often do you face this issue?

**Comment by euhruska** [comment]
I have seen this three times, the environment was same, but probably after a failed run. If it happens again, I will update

**Comment by vivek-bala** [comment]
Hmmm okay. If it was situation where you did ctrl+c (multiple times) or ctrl+z, its possible that the rmq server was not completely cleaned. Keep me posted
