### ISSUE TITLE
sim_task.cores = 1

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#45]
Can I set sim_task.cores = 1 if I want to run a different MD simulation on each core?

**Comment by vivek-bala** [comment]
Yes but it depends if the system will allow. In the last month, we learnt that BW does not allow multiple aprun commands to execute concurrently on the same node.  So if you set simulation tasks to use 1 core each on BW (which has 32 logical cores per node) and use aprun as the launch method, the 32 tasks that land on the same node will execute sequentially.

My quick advice for BW will be to use the entire node for each task when you have multiple tasks to execute concurrently.

**Comment by euhruska** [comment]
Good to know, I tried setting to 1 and looked like execute concurrently

**Comment by euhruska** [comment]
if BW has 32 logical cores, should I set sim_task.cores = 32? Before it was set to 16

**Comment by vivek-bala** [comment]
> if BW has 32 logical cores, should I set sim_task.cores = 32? Before it was set to 16

Yes

**Comment by vivek-bala** [comment]
> Good to know, I tried setting to 1 and looked like execute concurrently

Do you mean you observed it to be concurrent or you were expecting it to be concurrent?

**Comment by euhruska** [comment]
Most units did first nothing, only a couple of units ran and then finished, then more units ran. So I observed a concurrent behavior.

**Comment by vivek-bala** [comment]
The concurrent units might have been on different nodes. The units that didn't run (but you expected them to) might have landed on the same node.

**Comment by euhruska** [comment]
yeah

**Comment by andre-merzky** [comment]
Vivek, can you remind me why ORTE is not an option in this setting?

**Comment by vivek-bala** [comment]
I think it could be. I commented in #44 regarding that. I think it might require recompiling gromacs (and any analysis tools) with the openmpi that RP uses.

**Comment by euhruska** [comment]
I don't need gromacs
