### ISSUE TITLE
gpu unit settings

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#50]
Since the issue https://github.com/radical-collaboration/extasy-grlsd/issues/22 is so long, here I want to debug the inner GPU MD units.

1) Despite setting in extasy_grlsd.py 
```
sim_task.gpu_reqs = { 'processes': 1,
                                    'process_type': None,
                                    'threads_per_process': 1,
                                    'thread_type': None
                                }
```
, so why is in the unit*.sh file of the MD units there an ```aprun -n 2 -N 2 ```, why? I wante to use 1 CPU and 1 GPU on 1 node per unit.

2) the unit*.sh file misses an ```module load cudatoolkit```, has to be added in ``` sim_task.pre_exec```
3) I tried on a single interactive node (no extasy, manual) to run 
```/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 -N 1 -d 1 /sw/bw/bwpy/0.3.0/python-single/usr/bin/python test.py > test_out.txt``` but it once took like 5 min just to start up and second time didn't run at all.

**Comment by euhruska** [comment]
2) fixed but openmm does not find GPU

**Comment by andre-merzky** [comment]
@euhruska: can you please set `export RADICAL_PILOT_RECORD_SESSION=record` and run the test again?  After that, you should find a directory `record/` in your current directory - please pack that up and attach to the ticket, and I'll check whats up with the aprun parameters.  What is the stack you use?

**Comment by euhruska** [comment]
I have rerun it and now I don't see any units at all, no other changes made.
[record.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1871209/record.zip)
[re.session.leonardo.rice.edu.eh22.017624.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1871212/re.session.leonardo.rice.edu.eh22.017624.0004.zip)
[rp.session.leonardo.rice.edu.eh22.017624.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1871213/rp.session.leonardo.rice.edu.eh22.017624.0005.zip)

radical-stack
```
  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy5

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@feature-gpu
  radical.pilot        : 0.47-0.47-154-g98884456@feature-gpu
  radical.utils        : 0.47.3-v0.47.3@devel
  saga                 : 0.47-v0.46-72-gc86187fb@fix-issue_663
```

**Comment by andre-merzky** [comment]
Alas, I can't say much on why no units got submitted this time around - the  pilot is submitted and starts running all right, and the switch to `PMGR_ACTIVE` state is reported to EnTK all right.  @vivek-bala: any opinion?

**Comment by vivek-bala** [comment]
Baah, I am not able to reproduce this issue. @euhruska shall we meet online and work through this? How does 4pm CST tomorrow sound?

**Comment by euhruska** [comment]
Ok

**Comment by euhruska** [comment]
changing the python environment fixed 3)
vivek fixed 1)
Now it shows
4)
```Could not find nvcc.  Using runtime compiler, which may produce slower performance.  Set OPENMM_CUDA_COMPILER to specify where nvcc is located.```

5)
The speed in a single run for different conformations randomly changes between 104 ns/day and 610 ns/day. Not sure why, but it's a big difference.

**Comment by andre-merzky** [comment]
4 sounds like a  module load problem, doesn't it?  Shouldn't the `cudatoolkit` module provide nvcc?
