### ISSUE TITLE
correct version of radical.pilot

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#54]
Tried git pull the latest version of the fix-bw_python_interpreter branch of radical.pilot, but got:
```
Your configuration specifies to merge with the ref 'refs/heads/fix/bw_python_interpreter'
from the remote, but no such ref was fetched.
```
Is the bw_python_interpreter branch still correct

**Comment by andre-merzky** [comment]
Hi Eugen - those changes have been merged and released by now, you should be able to use the released RCT stack at this point.
