### ISSUE TITLE
md simulation speed fluctuates

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#55]
The sim_task simulates many md trajectories one after another, but there is a high variation how long this takes. Changes from 103 ns/day to 600ns/day and back. Is this a bw issue or settings issue?
```1000,603.768781415,291.373240389
Integrated 1000 steps in 0.672973 seconds
641.928 ns/day
(Quantity(value=603.7687814154779, unit=kilojoule/mole), Quantity(value=317.36253697425127, unit=kilojoule/mole))
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,594.801503522,313.089288498
Integrated 1000 steps in 4.16938 seconds
103.613 ns/day
(Quantity(value=594.801503521744, unit=kilojoule/mole), Quantity(value=341.015567402776, unit=kilojoule/mole))
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,599.644723976,337.775138949
Integrated 1000 steps in 0.730688 seconds
591.224 ns/day
```

**Comment by euhruska** [comment]
For longer trajectories the difference is 6 seconds to 41 seconds, so probably not caused by variation in the wait time to start the simulation, but by different speeds of simulation

**Comment by euhruska** [comment]
could write that trajectory to /tmp on a compute node, and copy the saved trajectory to Lustre before leaving the aprun session.

**Comment by vivek-bala** [comment]
I agree with your analysis, it is most likely caused by the heterogeneity of the compute nodes which leads to different simulation speeds.

> could write that trajectory to /tmp on a compute node, and copy the saved trajectory to Lustre before leaving the aprun session.

I think yes, you can do that.

**Comment by euhruska** [comment]
fixed by https://github.com/pandegroup/openmm/issues/2148
