### ISSUE TITLE
os.system call environment inherited?

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#57]
in unit post_ana_task I call the script https://github.com/radical-collaboration/extasy-grlsd/blob/master/helper_scripts/post_analyze.py, where os.system calls ```OMP_NUM_THREADS=1 python selection-cluster.py```. Will the environment in the unit be inherited to the os.system call, or not? Is this a good idea or should I split this unit into 3?

**Comment by euhruska** [comment]
it works, but unclear if the python script runs on login node or compute nodes

**Comment by vivek-bala** [comment]
The script will run on the compute node but I am unsure of the environment. os.system forks a new process and runs the executable inside it. How are you think of proceeding on this?

**Comment by euhruska** [comment]
ok, since the os.system runs the executable on the compute node, I don't think there is an issue. There are no error about the environment, so probably it's the same as the unit
