### ISSUE TITLE
partially quiet failure?

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#58]
is it possible that a partially quiet failure happens if unit.copy_input_data fails since the file doesn't exist? 
That unit had on the remote side nothing inside.

**Comment by vivek-bala** [comment]
You are right. Staging failures are by default non-fatal.

**Comment by euhruska** [comment]
do they leave warnings?

**Comment by euhruska** [comment]
makes it bit hard to debug this
