### ISSUE TITLE
can't restart a simulation

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#6]
extasy_grlsd.py assumes cur_iter = 0, but gromacslsdmap.wcfg has an start_iter which can be non-zero. So currently the simulation cannot be restarted

**Comment by vivek-bala** [comment]
You are right. I did not plan to add the restart capability in the first draft of the script. Do you want to take a crack at it or would you like me to work on it?

**Comment by euhruska** [comment]
each restart will have a new rp.session, and will upload and download shared data, which unnecessary delays everything. @vivek-bala is there a way to make all rp.sessions have the same shared data, or continue working in the old rp.session directory?

**Comment by andre-merzky** [comment]
You may want to have a look at the `resource://` type of staging URLs, which would point to a location which persists over subsequent RP sessions.  See [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/staging_directives.py#L121).

**Comment by euhruska** [comment]
sounds exactly like what I searched for

**Comment by euhruska** [comment]
@andre-merzky is there a command to wipe the resource:// clean?

**Comment by andre-merzky** [comment]
@euhruska : no, we don't have that.  Support for that staging level has only recently been added, so we did not yet gather much experience with that.

Having said that, I can probably implement something simple in the course of next week - like `pilot.purge_staging('resource://' | 'pilot://')`.  Until then you'll have to clean it out manually I'm afraid...

**Comment by euhruska** [comment]
thanks, it probably nice to have, but low priority. I think I will do by just creating a clean directory in resource:// for every new project and reconnect with old directories to extend

**Comment by vivek-bala** [comment]
Andre is correct in that we should use the ```resource``` staging directive, but it is not supported in EnTK currently. My advise would be to copy the data at the end of each task to a known location. For example,

```
task.copy_output_data = ['out.gro > /home/vivek91/shared_data_blue_waters/out_%s_%s.gro'%(trial_num, task_num)]
```

You can copy this data as input in the next trial by accessing the same location using the ```copy_input_data``` property of a task.

Let me know if that works for you temporarily.

**Comment by euhruska** [comment]
working in branch openmm, pending resolution of issue https://github.com/radical-collaboration/extasy-grlsd/issues/32
