### ISSUE TITLE
stops launching units

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#61]
This entk script ```python extasy_grlsd.py --Kconfig settings_ala12-gpu-big.wcfg``` runs 22 units of md simulation without a problem, but it's supposed to run 50 units in this task. I don't see where the problem happened.

[re.session.leonardo.rice.edu.eh22.017751.0022.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2275445/re.session.leonardo.rice.edu.eh22.017751.0022.zip)
[rp.session.leonardo.rice.edu.eh22.017751.0023.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2275446/rp.session.leonardo.rice.edu.eh22.017751.0023.zip)

**Comment by vivek-bala** [comment]
Can you attach the EnTK log messages from standard output and the link to the EnTK script please? Thanks!

**Comment by euhruska** [comment]
Here, launched 13 out of 50 units, entk script https://github.com/radical-collaboration/extasy-grlsd/blob/master/extasy_tica.py
logs:
[re.session.leonardo.rice.edu.eh22.017756.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2284173/re.session.leonardo.rice.edu.eh22.017756.0004.zip)
[rp.session.leonardo.rice.edu.eh22.017756.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2284174/rp.session.leonardo.rice.edu.eh22.017756.0005.zip)
[entk.log](https://github.com/radical-collaboration/extasy-grlsd/files/2284175/entk.log)

**Comment by euhruska** [comment]
solved by https://github.com/radical-collaboration/extasy-grlsd/issues/52
