### ISSUE TITLE
wrong number of nodes requested on bw

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#62]
I requested ```{'project': 'bamm', 'queue': 'high', 'resource': 'ncsa.bw_aprun', 'cpu_processes': 16, 'gpus': 4, 'cores': 64, 'access_schema': 'gsissh', 'cpus': 64, '
walltime': 30}```, which with 16 cpus per node are 4 nodes but on bluewaters I see that this job requested only 2 nodes. 
I had to use entk release 0.6.1 because https://github.com/radical-collaboration/extasy-grlsd/issues/52 isn't resolved yet. Is this issue caused by the old entk version?

**Comment by vivek-bala** [comment]
BW compute node has hyper-threading so consider it to have 32 cores per node.

**Comment by euhruska** [comment]
so should request 32 core but 16 cpus per GPU (xk/GPU nodes)?

**Comment by vivek-bala** [comment]
I believe so yes.

**Comment by euhruska** [comment]
fixed with https://github.com/radical-collaboration/extasy-grlsd/issues/52
