### ISSUE TITLE
add pyemma module

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#7]
The new selection.py will use clustering with the python module pyemma. Currently the python there doesn't have pyemma and there are no instructions how to add it.

**Comment by vivek-bala** [comment]
I suppose you will have to install pyemma on Blue waters (conda or pip?). You can then change the task.pre_exec in the extasy script to load the same environment.

**Comment by euhruska** [comment]
the post_ana_task has already your python environment, so I tried pip install pyemma on it, but got permissions denied. Not sure if easier make a new post_ana_task environment.
 (But conda would have been preferred, but didn't find conda)

**Comment by vivek-bala** [comment]
I will suggest creating your conda env or virtualenv on Blue Waters in which you can install lsdmap or pyemma. You can set global read permissions on it if you would like to share it with someone. You can put the commands to activate the conda env / virtualenv in the pre_exec of the post_ana_task (or any task where you require that environment).

Let me know how it goes.

**Comment by euhruska** [comment]
see branch 'no_fail'
