### ISSUE TITLE
module load error

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#80]
When I load these modules standalone, I have no issues.
```
module swap PrgEnv-cray PrgEnv-gnu ||  (echo "pre_exec failed"; false) || exit
module load bwpy/1.2.5 ||  (echo "pre_exec failed"; false) || exit
module add bwpy-mpi 
``` 
but with entk it leads to STDERR:
```
ModuleCmd_Switch.c(179):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
bwpy/1.2.5(16):ERROR:150: Module 'bwpy/1.2.5' conflicts with the currently loaded module(s) 'bwpy/1.2.4'
bwpy/1.2.5(16):ERROR:102: Tcl command execution failed: conflict bwpy
```
Why is there a difference? I didn't load any bwpy/1.2.4 before in that unit so where did it come from? This is non-fatal

**Comment by vivek-bala** [comment]
Probably a default when you log into BW. Try:
```
module unload bwpy/1.2.4
module load bwpy/1.2.5
```

or 
```
module swap bwpy/1.2.4 bwpy/1.2.5
```

Same for #81

**Comment by euhruska** [comment]
default, have to unload

**Comment by euhruska** [comment]
hmm, it;s a fix, but when I run standalone ob bw this doesn't happen

**Comment by vivek-bala** [comment]
Did you try standalone on the login node or the compute node? They might have different environments.

**Comment by euhruska** [comment]
I tested it with on a small job on compute node
