### ISSUE TITLE
speed difference rp and standalone

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#83]
My issue is that standalone openmm (aprun on a separate script) leads to 250ns/day, but the same commands with radical-pilot barely 23ns/day.

The md.log in /mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/rp.session.leonardo.rice.edu.eh22.017787.0007/pilot.0000/unit.000005
 shows the radical-pilot results. The unit*.sh script gives the module load commands. In the standalone case I was running the commands in unit*.sh, without  -L 7063 in aprun, but including loading the RP variables, but that gave a 10x faster speed

**Comment by euhruska** [comment]
removed bwpy-environ, but didn't help

**Comment by andre-merzky** [comment]
I don't have permissions to access the unit script - can you please attach that, and also the  the aprun script you used for manual testing?  Thanks!

**Comment by euhruska** [comment]
extasy:
[unit.000005.txt](https://github.com/radical-collaboration/extasy-grlsd/files/2383367/unit.000005.txt)
standalone:
[unit.000005.pbs.txt](https://github.com/radical-collaboration/extasy-grlsd/files/2383366/unit.000005.pbs.txt)

**Comment by euhruska** [comment]
is there a way to change "-cc 0" to "-cc none" in the aprun command in entk?

**Comment by andre-merzky** [comment]
Those two scripts result in different performance??  That is really surprising.  Could you do me the favor, and pack up the whole pilot sandbox, including all units subdirs?  Thanks!

**Comment by euhruska** [comment]
hmm, I when I ran it interactively I removed traj writing, so that caused the difference.
