### ISSUE TITLE
remove two.radical-project.org

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#85]
Currently the appman is:
```
appman = AppManager(hostname='two.radical-project.org', port=33134)#port=args.port)
```
How can I convert that to my own setup? @vivek-bala

**Comment by vivek-bala** [comment]
Basically that's the hostname for the machine where your RabbitMQ docker process is running and the corresponding port via which it can be accessed. If you want to setup RabbitMQ on a different machine, please see https://radicalentk.readthedocs.io/en/latest/install.html#installing-rabbitmq

Let me know how it goes.

**Comment by euhruska** [comment]
I have my own local rabbitmq installed, what would be the correct setting for the AppManager then?

**Comment by vivek-bala** [comment]
The default for rabbitmq should be 'localhost' and '5672' which you can use the hostname and port respectively.

**Comment by euhruska** [comment]
is it possible that the port is '25672'
```
lsof -i | grep beam
beam.smp  10059 eh22   59u  IPv4 23378880      0t0  TCP *:25672 (LISTEN)
beam.smp  10059 eh22   60u  IPv4 23378882      0t0  TCP localhost:59955->localhost:epmd (ESTABLISHED)
beam.smp  10059 eh22   61u  IPv4 23378884      0t0  UDP *:39475
beam.smp  10059 eh22   69u  IPv6 23379151      0t0  TCP *:amqp (LISTEN)
```

**Comment by euhruska** [comment]
with '5672' it doesn't work

**Comment by euhruska** [comment]
works now
