### ISSUE TITLE
pilot launches no units

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#94]
pilot is running, but there are no units launched. On the remote agent_0.log is created, but not bootstrap*.log
[rp.session.leonardo.rice.edu.eh22.017799.0006.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2416218/rp.session.leonardo.rice.edu.eh22.017799.0006.zip)

**Comment by andre-merzky** [comment]
The pilot logs give no indication of any units arriving - the problem is likely to be found on the client side, you may want to check the log files for `ERROR` messages.

**Comment by euhruska** [comment]
Haven't found any ERROR messages in the local rp directory
[rp.session.leonardo.rice.edu.eh22.017799.0006-local.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2416381/rp.session.leonardo.rice.edu.eh22.017799.0006-local.zip)

**Comment by andre-merzky** [comment]
Indeed - but there is also no sign of any units being submitted.  @vivek-bala , do you have any idea what could be up with EnTK not submitting any units?

**Comment by euhruska** [comment]
restarting resolved this
