### ISSUE TITLE
which commit used

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#99]
when radical stack says
radical.entk         : 0.7.5-0.7.3-19-g383ebea1@devel
how do I find the commit which was used?
I didn't find a commit with g383ebea1 in it
It might be easier to reproduce errors/working envirornments if one can find the exact commit which was used.

**Comment by andre-merzky** [comment]
This is exactly why we have `radical-stack` :-)  In your example, the used commit is `383ebea1`.  The leading `g` is added by git to mark this as a git hash (AFAIU).

**Comment by andre-merzky** [comment]
I should add: in your example, you are on version `0.7.5` (this is the content of the `VERSION` file, which is `19` commits beyond the last version tag (`0.7.3`).

**Comment by euhruska** [comment]
ah, the ```g``` threw me of. thanks
